# Generated by Django 4.1.5 on 2023-03-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.BigIntegerField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
