# Generated by Django 4.1.5 on 2023-03-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_order_customer_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
